version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:

  install:
    runtime-versions:
      java: corretto17
      python: 3.11
    commands:
      - echo "Installing required tools..."

      - echo "Installing Trivy..."
      - TRIVY_VERSION=0.56.2
      - wget -q https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/trivy
      - trivy --version

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

      - echo "Preparing Docker image tag..."
      - export IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"
      - export IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/swiggy-clone:$IMAGE_TAG"

      - echo "Image to build:"
      - echo "$IMAGE_NAME"

  build:
    commands:
      - echo "Build started on $(date)"
      
      - echo "Building Docker image..."
      - docker build -t "$IMAGE_NAME" .

      - echo "Running Trivy security scan..."
      - trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress "$IMAGE_NAME"

      - echo "Trivy scan passed."
      - echo "Pushing Docker image to Docker Hub..."
      - docker push "$IMAGE_NAME"

      - echo "Saving image tag for CodeDeploy..."
      - echo "$IMAGE_TAG" > image_tag.txt

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Docker image:"
      - echo "$IMAGE_NAME"
      - echo "Image tag:"
      - cat image_tag.txt

artifacts:
  files:
    - appspec.yml
    - image_tag.txt
    - scripts/**/*
    - Dockerfile
    - '**/*'
  discard-paths: no
